### ISSUE TITLE
Cannot override/set jwt.secret with 7.0.0-M3

### ISSUE THREAD

**Issue by ZenHarbinger** [grails-plugins/grails-spring-security-core#1114]
### Expected Behavior

in application.yml with the following settings:
```
grails:
  plugin:
    springsecurity:
      rest.token.storage.jwt:
        privateKeyPath: /pub/private_key.der
        publicKeyPath: /pub/public_key.der
        secret: cFFqts8#7PI#JefB!v0j2fjhy6ZuYG0N

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
```

The application should load my settings.

### Actual Behaviour

```
Caused by: java.lang.IllegalStateException: java.lang.Exception: A JWT secret must be defined. Please provide a value for the config property: grails.plugin.springsecurity.rest.token.storage.jwt.secret
```
Stepping through the code, no values in the config are as read from my file.

### Environment Information

- Linux
- Corretto JDK 17.0.15

### Version

7.0.0-M3

**Comment by jdaugherty** [comment]
Have you tried expanding the dots?  The key path looks wrong to me.

Can you please provide a reproducible project?  The functional tests are passing so I suspect it's your syntax of the config path.

**Comment by ZenHarbinger** [comment]
```
grails:
  plugin:
    springsecurity:
      rest:
        token:
          storage:
            jwt:
              privateKeyPath: /pub/private_key.der
              publicKeyPath: /pub/public_key.der
              secret: 'cFFqts8#7PI#JefB!v0j2fjhy6ZuYG0N'
```
Fails too
