### ISSUE TITLE
@Secured annotation not working for namespaced controllers v3.0.1

### ISSUE THREAD

**Issue by xhkz** [grails-plugins/grails-spring-security-core#406]
Same issue as https://github.com/grails-plugins/grails-spring-security-core/issues/212

v3.0.0.M1 works fine with namespaced controller.

**Comment by alvarosanchez** [comment]
We have functional tests to cover namespaced controllers, eg: https://github.com/grails-plugins/grails-spring-security-core/blob/master/functional-test-app/grails-app/controllers/namespaced/secure/NamespacedController.groovy and its test: https://github.com/grails-plugins/grails-spring-security-core/blob/master/functional-test-app/src/integration-test/groovy/specs/NamespaceSecuritySpec.groovy#L125-L131

Can you please upload an example that reproduces the issue?

**Comment by xhkz** [comment]
Hi alvaro,

```groovy
@Secured(['ROLE_ADMIN'])
class ConfigController {
    def index() {
        render view: "index"
    }
}
```

```groovy
@Secured(['ROLE_ADMIN'])
class TestController {
    static namespace = 'config'

    def index() {
        render view: "index"
    }
}
```

We have admin and user roles, if I login with user role, it can not visit url/config, but url/config/test still could be viewed.

**Comment by alvarosanchez** [comment]
We need to see configuration, URL mappings, etc.

**Comment by xhkz** [comment]
UrlMappings:
```groovy
        "/$controller/$action?/$id?(.$format)?" {
            constraints {
            }
        }

        "/config/$controller/$action?/$id?(.$format)?" {
			constraints {
			}
        }
```

application.yml
```yml
grails:
  plugin:
    springsecurity:
      debug:
        useFilter: true
      rejectIfNoRule: false
      fii:
        rejectPublicInvocations: true
      userLookup:
        userDomainClassName: 'com.test.User'
        usernamePropertyName: 'username'
        authorityJoinClassName: 'com.test.UserRole'
      authority:
        className: 'com.test.Role'
      logout:
        postOnly: false
      controllerAnnotations:
        staticRules:
          - pattern: '/error'
            access: 'permitAll'
          - pattern: '/assets/**'
            access: 'permitAll'
          - pattern: '/**/js/**'
            access: 'permitAll'
          - pattern: '/**/css/**'
            access: 'permitAll'
          - pattern: '/**/images/**'
            access: 'permitAll'
          - pattern: '/**/favicon.ico'
            access: 'permitAll'
          - pattern: '/**'
            access: 'isFullyAuthenticated()'
```

I've also tried adding 
```yml
          - pattern: '/config/**'
            access: 'ROLE_ADMIN'
```

with v3.0.0.M1, only staticRules are in different format:
```yml
                staticRules:
                    /error:           ['permitAll']
                    /login:           ['permitAll']
                    /logout:          ['permitAll']
                    /assets/**:       ['permitAll']
                    /**/js/**:        ['permitAll']
                    /**/css/**:       ['permitAll']
                    /**/images/**:    ['permitAll']
                    /**/favicon.ico:  ['permitAll']
                    /**:              ['IS_AUTHENTICATED_FULLY']
```

Thanks for your time.
