### ISSUE TITLE
spring security plugin 3.1.1 not working with grails 3.2.8

### ISSUE THREAD

**Issue by danleahy** [grails-plugins/grails-spring-security-core#470]
Previously i have successfully used spring security plugin 3.1.1 with Grails 3.2.4

I have just attempted to use it with Grails 3.2.8 but it doesn't work

What i see is that password is not encoded in  grails 3.2.8 because the springSecurityService injected service is null in the User.groovy created by the s2-quickstart grails 

running this on windows 10 pro 

testspringsecurity2 environment 
| Grails Version: 3.2.4
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_111

testsecurity3 environment
| Grails Version: 3.2.8
| Groovy Version: 2.4.10
| JVM Version: 1.8.0_111

[testsecurity3.zip](https://github.com/grails-plugins/grails-spring-security-core/files/903241/testsecurity3.zip)
[testspringsecurity2.zip](https://github.com/grails-plugins/grails-spring-security-core/files/903242/testspringsecurity2.zip)

**Comment by jameskleeh** [comment]
Autowiring was turned off by default: 
```
grails:
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false  
```

Re-enable it to restore the previous behavior.
