### ISSUE TITLE
s2-quickstart generates invalid User domain class

### ISSUE THREAD

**Issue by uehaj** [grails-plugins/grails-spring-security-core#475]
In grails 3.2.8, create-app generates application.yaml  to:

```
grails:
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false
```
where 'autowired: false' means auto injection to domain class field is disabled at default.

But In User.groovy domain class,

```

@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

	private static final long serialVersionUID = 1

	transient springSecurityService

:

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}

	static transients = ['springSecurityService']
```

This can't work because springSecurityService is not wired because of Grails autoWired default value is false, so the password field always to be null. (of course authentications fails always too) .
