### ISSUE TITLE
Version 5.0.0 of plugin - Cannot set configuration override in application.yml or application.groovy

### ISSUE THREAD

**Issue by boardbloke** [grails-plugins/grails-spring-security-core#724]
### Expected Behavior

I have set some spring-security-core overrides in application.yml thus:
```
grails:
    plugin:
        springsecurity:
            userLookup:
                userDomainClassName: test.User
                usernamePropertyName: username
                passwordPropertyName: passwd
                enabledPropertyName: enabled
                accountExpiredPropertyName: accountExpired
                accountLockedPropertyName: accountLocked
                passwordExpiredPropertyName: passwordExpired
                authoritiesPropertyName: authorities
                authorityJoinClassName: test.UserRole
```

But they are not being picked up.  The code in ReflectionUtils.getSecurityConfig appears to be the problem.  Its doing:
```
grailsConfig.getProperty('grails.plugin.springsecurity', ConfigObject.class)
```
and that is returning null

If I debug and evaluate the following instead, it works:
```
grailsConfig.grails.plugin.springsecurity
```

As does:
grailsConfig.getProperty('grails.plugin.springsecurity', org.grails.config.NavigableMap.class)

### Steps To Reproduce

Create grails app with 5.0.0 version of spring security plugin

Add the overrides to the application.yml

Start app and debug into ReflectionUtils.getSecurityConfig()

### Version

5.1.2
