### ISSUE TITLE
Error Publishing Release

### ISSUE THREAD

**Issue by puneetbehl** [grails-plugins/grails-spring-security-core#950]
### Expected Behavior

We should be able to publish a release.

### Actual Behaviour

It appears that the release workflow is failed to resolve the current release version from the GITHUB_REF in the following step:

```
Run echo "release_version=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
  echo "release_version=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash -e {0}
  env:
    GIT_USER_NAME: puneetbehl
    GIT_USER_EMAIL: behlp@objectcomputing.com
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.6-10.1/x64
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.6-10.1/x64
```

See the build log at https://github.com/grails/grails-spring-security-core/actions/runs/6550599061/job/17790046467 for complete details.
